# Generated by Django 4.0 on 2022-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='teste',
            field=models.CharField(default='1', max_length=2, verbose_name='teste'),
        ),
    ]
